[package]
name = "vm"
version = "0.1.0"
edition = "2021"
default-run = "main"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "asm"

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.86"
